Create Models and Controller
Lemaitin/Task_Manager pull request #1
Opened 2021-08-11 17:30 UTC by Lemaitin

2021-08-11 17:49 UTC, Druid-Team-Lead commented
Please add .gitignore file to the project.
Example: https://github.com/github/gitignore/blob/master/VisualStudio.gitignore

2021-08-11 21:20 UTC, Druid-Team-Lead requested changes
Please add .gitignore file to the project.
Example: https://github.com/github/gitignore/blob/master/VisualStudio.gitignore

2021-08-11 21:20 UTC, dasokume commented on ToDoApi/ToDoApi/Startup.cs
> +			//services.AddDatabaseDeveloperPageExceptionFilter();
Do we need this?

2021-08-11 21:20 UTC, dasokume commented on ToDoApi/ToDoApi/Models/TodoItem.cs
> +using System.Linq;
Remove unused **using**

2021-08-11 21:20 UTC, dasokume commented on ToDoApi/ToDoApi/Models/TasksContext.cs
> +        public DbSet<TodoItem> Tasks { get; set; }
Add extra empty line here

2021-08-11 21:20 UTC, dasokume commented on ToDoApi/ToDoApi/Models/TasksContext.cs
> +        }
Here as well

2021-08-11 21:20 UTC, dasokume commented on ToDoApi/ToDoApi/Controllers/TodoController.cs
> +            db = context;
Remove from the constructor. Create a new class called DB initializer

2021-08-11 21:20 UTC, dasokume commented on ToDoApi/ToDoApi/Controllers/TodoController.cs
> +        // POST api/tasks
Delete comments

2021-08-11 21:20 UTC, dasokume commented on ToDoApi/ToDoApi/Controllers/TodoController.cs
> +        }
Add extra empty line

2021-08-11 21:20 UTC, dasokume commented on ToDoApi/ToDoApi/Controllers/TodoController.cs
> +            TodoItem task = await db.Tasks.FirstOrDefaultAsync(x => x.Id == id);
Create TodoItemRepository class to work with DB.
Create TodoItemService class to work with the repository.
Use this new service in your controller

2021-09-12 15:59 UTC, Druid-Team-Lead requested changes

2021-09-12 15:59 UTC, dasokume commented on ToDoApi/ToDoApi/Startup.cs
> +			services.AddDbContext<TasksContext>(x => x.UseSqlServer("Data Source=MEGATA4KA;Initial Catalog=TaskManager;Integrated Security=True;Connect Timeout=30;"));
Move connection string to appsettings.json file

2021-09-12 15:59 UTC, Druid-Team-Lead commented on ToDoApi/ToDoApi/Context/TodoDbContext.cs
> +        public DbSet<TodoItem> TodoItems { get; set; }
Add empty line

2021-09-12 15:59 UTC, Druid-Team-Lead commented on ToDoApi/ToDoApi/Context/TodoDbContext.cs
> +        protected override void OnModelCreating(ModelBuilder modelBuilder)
Add empty line

2021-09-12 15:59 UTC, Druid-Team-Lead commented on ToDoApi/ToDoApi/Controllers/TodoController.cs
> +    [Route("api/[controller]")]
Fix formatting in this file

2021-09-12 15:59 UTC, Druid-Team-Lead commented on ToDoApi/ToDoApi/Models/TodoItem.cs
> +	public class TodoItem
Fix formatting

2021-09-12 15:59 UTC, Druid-Team-Lead commented on ToDoApi/ToDoApi/Models/TodoItem.cs
> +        public int Id { get; set; }
Add empty line between properties

2021-09-12 15:59 UTC, Druid-Team-Lead commented on ToDoApi/ToDoApi/Repository/Interfaces/ITodoItemRepository.cs
> +using System.Linq;
Remove unused using

2021-09-12 15:59 UTC, Druid-Team-Lead commented on ToDoApi/ToDoApi/Repository/Interfaces/ITodoItemRepository.cs
> +        Task<IEnumerable<TodoItem>> GetItemList();
Add empty line between methods

2021-09-12 15:59 UTC, Druid-Team-Lead commented on ToDoApi/ToDoApi/Service/Interfaces/ITodoService.cs
> +using System.Linq;
Remove unused using

2021-09-12 15:59 UTC, Druid-Team-Lead commented on ToDoApi/ToDoApi/Service/Interfaces/ITodoService.cs
> +		Task<IEnumerable<TodoItem>> GetItemList();
Add empty line between methods

2021-09-12 15:59 UTC, Druid-Team-Lead commented on ToDoApi/ToDoApi/Service/TodoService.cs
> +		}
Add empty line

2021-09-12 15:59 UTC, Druid-Team-Lead commented on ToDoApi/ToDoApi/Startup.cs
> +		// This method gets called by the runtime. Use this method to add services to the container.
Remove trash comments in file

2021-09-12 16:13 UTC, Druid-Team-Lead requested changes

2021-09-12 16:13 UTC, Druid-Team-Lead commented on ToDoApi/ToDoApi/Controllers/TodoController.cs
> +			if (todoItem == null)
Empty line after service call and before return statement

2021-09-12 16:18 UTC, Druid-Team-Lead commented
Well done!

2021-09-12 16:18 UTC, Druid-Team-Lead approved these changes

2021-09-12 16:21 UTC, merged